### ISSUE TITLE
Web demo appears to be non-functional.

### ISSUE THREAD

**Issue by ciresnave** [hardboiled65/seshat-unicode#6]
The web demo listed in the readme does not appear to work.
It pops up with an error saying the application failed.

**Comment by ciresnave** [comment]
Minor correction... It specifically states the following:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by hardboiled65** [comment]
Sorry for the late response. I didn't get any notifications.
I already know that the demo doesn't work. The demo is maintained in another two repositories. One (https://github.com/hardboiled65/seshat-rest) for API server and one (https://github.com/hardboiled65/seshat-demo-web) for web front-end.
It seems the problem was the API server is down. And now Heroku has discontinued the free plan. Both side will not work.
The API backend was running on a cloud server which is currently not maintained.
Simply, the demo is totally unmaintained :(. Thanks for the issue. The link will be removed in the next commit.

**Comment by ciresnave** [comment]
Thank you for the response.  I mainly posted the issue to ensure you knew it was broken.  No worries about the late reply.  Most of us are busy.  I understand completely that the demo was not maintainable within the confines of your available time.  As I said, most of us are busy.  Thanks for letting me know why and what will become of it.
